"""modify matrix flows table add column name and desc

Revision ID: 0f45848433d1
Revises: 499903593ef0
Create Date: 2024-12-23 18:29:44.905678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f45848433d1'
down_revision: Union[str, None] = '499903593ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrixflows', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('matrixflows', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_matrixflows_name'), 'matrixflows', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matrixflows_name'), table_name='matrixflows')
    op.drop_column('matrixflows', 'description')
    op.drop_column('matrixflows', 'name')
    # ### end Alembic commands ###
