"""Add matrix flow table

Revision ID: cebd646dd7b6
Revises: 
Create Date: 2024-12-20 19:19:10.751203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebd646dd7b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matrixflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrixflows_id'), 'matrixflows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matrixflows_id'), table_name='matrixflows')
    op.drop_table('matrixflows')
    # ### end Alembic commands ###
